# Generated by Django 4.2.4 on 2023-09-03 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_nutritionplan_daily_carbs_nutritionplan_daily_fats_and_more'),
        ('users', '0002_userprofile_selected_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='selected_workouts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.nutritionplan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.workoutplan'),
        ),
    ]
