# Generated by Django 4.2.4 on 2023-09-03 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_fitnessgoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessgoal',
            old_name='goal_type',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='fitnessgoal',
            name='created_at',
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='current_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=12),
        ),
        migrations.AlterField(
            model_name='fitnessgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
