# Generated by Django 4.2.4 on 2023-09-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_goal_type_fitnessgoal_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workout_done', models.TextField(help_text='Workouts done on this date')),
                ('nutrition_taken', models.TextField(help_text='Nutrition taken on this date')),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='users.userprofile')),
            ],
        ),
    ]
