# Generated by Django 4.2.4 on 2023-09-03 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_nutritionplan_daily_carbs_nutritionplan_daily_fats_and_more'),
        ('users', '0006_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='trainers.trainerprofile'),
        ),
    ]
